name: Build and Test with macOS and clang
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        compiler: [gcc-9,  gcc-10]

    steps:

    - name: install-deps
      run: |
        if [[ ${{ matrix.os }} == "macos-10.15" ]]; then
          brew install doxygen
          brew install python3
          pip3 install setuptools
          pip3 install numpy
          pip3 install netCDF4
          if [[ ${{ matrix.compiler }} == "gcc-9" ]]; then
            sudo ln -sf /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
          elif  [[ ${{ matrix.compiler }} == "gcc-10" ]]; then
            sudo ln -sf /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
          fi
        fi

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: bufr
        submodules: true

    - name: build
      run: |
        if [[ ${{ matrix.compiler }} == "gcc-9" ]]; then
          export CC=clang
          export FC=gfortran-9
        elif [[ ${{ matrix.compiler }} == "gcc-10" ]]; then
          export CC=clang
          export FC=gfortran-10
        fi
        cd bufr
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=./install -DENABLE_PYTHON=ON ..
        make -j2
        make install

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/bufr/build
        ctest
